### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by pjbgf**
New versions:
- Golang version 1.20.3
- Trivy 0.39.1
- Alpine 3.17

### CODE REVIEW

**Comment by pjbgf** [comment]
@thomasferrandiz @matttrach what would be the next steps to get this merged?

**Comment by macedogm** [comment]
Regarding the Trivy bump, please see PR https://github.com/rancher/image-build-base/pull/36. I believe it's best to keep it on a separate PR.

CC @matttrach and @pjbgf

**Comment by matttrach** [comment]
First, @pjbgf, so sorry we have not responded! You are absolutely right that these dependencies need to be bumped. This image forms the base for many others that we use, so keeping its dependencies up to date is really important.

There are two things we are working on that affect this: 
1) we are currently working on rke2/k3s patch releases, which depend on this image
    - if upstream kubernetes updates their version of Go we may need to quickly update this repo and release a new version
    - when we do this we need the change to be atomic, which means that we can't pull any changes in until we know, which means basically this repo is frozen until patch releases are out
2) we are implementing a system to automatically keep dependencies up to date using dependabot and updatecli
    - if you take a look at PR #36 you can see the config we intend to add to keep Trivy up to date
    - I would like to take the time to write the updatecli configs to keep the other dependencies you mention here up to date as well
    - You can track progress on this [here](https://github.com/rancher/rke2/issues/4257)
 
 Thank you so much for the contribution, we will try to resolve these issues as soon as  possible.

**Comment by pjbgf** [comment]
@matttrach thank you for the clarifications. Closing this in favour of the upcoming automation.

**Pull request closed without merging**
